### ISSUE TITLE
Error with node-red

### ISSUE THREAD

**Issue by paulbdavis** [AYapejian/node-home-assistant#6]
Getting this error in the debug log of node-red

```
22 Jun 19:00:50 - [error] [server:Home Assistant] TypeError: states.reduce is not a function
    at _get.then.states (/data/node_modules/node-home-assistant/lib/ha-api.js:38:31)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by paulbdavis** [comment]
Nevermind, restarting node-red resolved the issue
